CREATE TABLE `online_payments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tenantId` int NOT NULL,
	`clientId` int NOT NULL,
	`chargeType` enum('product','appointment','subscription') NOT NULL,
	`referenceId` int,
	`asaasPaymentId` varchar(100),
	`asaasSubscriptionId` varchar(100),
	`asaasCustomerId` varchar(100),
	`billingType` enum('BOLETO','CREDIT_CARD','PIX','STORE') NOT NULL DEFAULT 'PIX',
	`amount` decimal(10,2) NOT NULL,
	`status` enum('pending','paid','overdue','refunded','cancelled') NOT NULL DEFAULT 'pending',
	`invoiceUrl` text,
	`pixQrCode` text,
	`pixCopyCola` text,
	`dueDate` date,
	`paidAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `online_payments_id` PRIMARY KEY(`id`)
);
